### ISSUE TITLE
Accepted techniques remain in the list

### ISSUE THREAD

**Issue by ghost** [mitre-attack/tram#70] opened 2021-02-24 10:11 UTC
I have found some solutions for the error already mentioned in some other issues and TRAM is finally starting now and rendering the text in the analyze procedure. 

Unfortunately suggested techniques remain in the list even after I accepted them. When I reject a technique it's being removed from the list, but when I accept it, it will be added to the Positives again and again so there are multiple entries and the original suggestion remains in the list. So I am not able to complete the review and all the reports remain in the "needs review" list.

![acceptedtechniques](https://user-images.githubusercontent.com/78904666/108985127-f738e000-7690-11eb-98ed-2d0e3bdec81d.JPG)

**Comment by jecarr** [comment] 2021-06-29 00:17
This is because the database will always add a new entry - no matter what - when you press these buttons. Statuses beyond 'Needs Review' are never used anyway (at time of writing). I've raised #86 and the tagged PR (in that issue's description) fixes both of these (duplicate confirmed entries and using statuses).

If the duplicate entries are really bugging you, one thing I can suggest is adding this small snippet in rest_svc.py, at the beginning of the true_positive() method (at time of writing, around [line 67](https://github.com/mitre-attack/tram/blob/master/service/rest_svc.py#L67))

```
async def true_positive(self, criteria=None):
    existing = await self.dao.get('report_sentence_hits', dict(uid=criteria['sentence_id'], attack_uid=criteria['attack_uid']))
    if existing:
        return
    <rest of method>
```

**Comment by MarkDavidson** [comment] 2021-10-06 12:05
Hello @timoliciouz and thank you for the bug report. TRAM has moved to https://github.com/center-for-threat-informed-defense/tram and this issue is no longer present in that repository so I am closing this issue. Thank you!

**Closed as completed by MarkDavidson** 2021-10-06 12:05 UTC
